### PR TITLE
Added solution for 4 problems in c++ section

### PR DESCRIPTION
**Pull request by psycho-valker**
My solution for some c++ questions.

### CODE REVIEW

**Comment by rajat19** [comment]
Please add your solutions and their problem link in readme as well.
It would be a great help

**Comment by psycho-valker** [comment]
Sure!!

**Comment by rajat19** [comment]
To increase your PR count
you can add another pr with readme updated for all 4 files
I would then approve both pr of yours

**Review by rajat19 — APPROVED** [review]
No readme yet

**Pull request merged**
