### PR TITLE
Simple Array Sum

### PR DESCRIPTION
**Pull request by mayankpathak4513**
In this Code we traverse all the array elements and find the sum of all the values.

### CODE REVIEW

**Comment by rajat19** [comment]
add extension to file
Also update readme for problem link

**Comment by mayankpathak4513** [comment]
Yeah sure will do the necessary

**Review by Sarcastic-dude — COMMENTED** [review]
Code looks good and Compiled Successfully.

**Comment by rajat19** [comment]
Code is part of `Algorithm/Warmup`
And cpp solution is already present in repo [Link to Solution](https://github.com/rajat19/Hackerrank/blob/master/Algorithms/Warmup/simple-array-sum.cpp)

Try submitting some other solution
Declining this PR

**Pull request closed without merging**
